export const LOCATION_LIST_REQUEST = 'LOCATION_LIST_REQUEST'
export const LOCATION_LIST_SUCCESS = 'LOCATION_LIST_SUCCESS'
export const LOCATION_LIST_FAIL = 'LOCATION_LIST_FAIL'

export const PROJECT_LIST_REQUEST = 'PROJECT_LIST_REQUEST'
export const PROJECT_LIST_SUCCESS = 'PROJECT_LIST_SUCCESS'
export const PROJECT_LIST_FAIL = 'PROJECT_LIST_FAIL'


export const BUILDING_LIST_REQUEST = 'BUILDING_LIST_REQUEST'
export const BUILDING_LIST_SUCCESS = 'BUILDING_LIST_SUCCESS'
export const BUILDING_LIST_FAIL = 'BUILDING_LIST_FAIL'


export const FLOOR_LIST_REQUEST = 'FLOOR_LIST_REQUEST'
export const FLOOR_LIST_SUCCESS = 'FLOOR_LIST_SUCCESS'
export const FLOOR_LIST_FAIL = 'FLOOR_LIST_FAIL'

export const CREATE_NEW_LOCATION_REQUEST = 'CREATE_NEW_LOCATION_REQUEST'
export const CREATE_NEW_LOCATION_SUCCESS = 'CREATE_NEW_LOCATION_SUCCESS'
export const CREATE_NEW_LOCATION_FAIL = 'CREATE_NEW_LOCATION_FAIL'